# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: hislopzach
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - hislopzach/disc-tracker
      - hislopzach/spotify-data-viewer

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Zach Hislop's Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "Zach Hislop"

# Tagline section text
tagline: >-
    >>>

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-medium"
      text: "Zach’s 2024 Tops"
      url: "https://medium.com/fridayswell/zachs-2024-tops-99bacfcfb9be"
      alt: "Zach’s 2024 Tops"
      title: "Zach’s 2024 Tops"
      target: "_blank"
  - link:
      icon: "fa-brands fa-medium"
      text: "Zach’s 2023 Top Adventures: Near and Far"
      url: "https://medium.com/fridayswell/zachs-top-5-2023-top-5-adventures-08d3c3d4e691"
      alt: "Zach’s 2023 Top Adventures: Near and Far"
      title: "Zach’s 2023 Top Adventures: Near and Far"
      target: "_blank"
  - link:
      icon: "fa-brands fa-medium"
      text: "2021 Top 5: A Podcast, Album, Song, Book, and a Daily Practice"
      url: "https://medium.com/fridayswell/zachs-top-5-2023-top-5-adventures-08d3c3d4e691"
      alt: "2021 Top 5"
      title: "2021 Top 5"
      target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-medium"
      url: "https://medium.com/@hislopzach"
      title: "Zach's Medium"
      alt: "Zach's Medium"
      target: "_blank"
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/hislopzach"
      title: "Zach's GitHub"
      alt: "Zach's GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/zachary-hislop/"
      title: "Zach's LinkedIn"
      alt: "Zach's LinkedIn"
      target: "_blank"
  - social:
      icon: "fa-brands fa-spotofy"
      url: "https://open.spotify.com/user/12165262893"
      title: "Zach's Spotify"
      alt: "Zach's Spotify"
      target: "_blank"
#   - social:
#       icon: "fa-solid fa-envelope"
#       url: "mailto:zhgchgli@gmail.com"
#       title: "Email: zhgchgli@gmail.com"
#       alt: "zhgchgli@gmail.com"
#       target: "_blank"

# Footer text
# footer: >
#     Hi there! Follow me on Medium or GitHub, or stay connected on Instagram or LinkedIn.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2024 Zachary Hislop. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
